version: '3'

services:
  web:
    build:
      context: .
      args:
        http_proxy: ${BUILD_PROXY}
        https_proxy: ${BUILD_PROXY}
        HTTP_PROXY: ${BUILD_PROXY}
        HTTPS_PROXY: ${BUILD_PROXY}
    command: bundle exec rails s -b '0.0.0.0'
    volumes:
      - .:/app
      - bundle:/bundle
    ports:
      - 3000:3000
    depends_on:
      - db

  db:
    image: mysql:5.7.16
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: 123123
    volumes:
      - mysql_data:/var/lib/mysql
    # ports:
    #   - 3306:3306

volumes:
  bundle:
  mysql_data:
